resolver: lts-18.11

packages:
- '.'

extra-deps: [
  hakyll-4.14.1.0,
  #hakyll-sass-0.2.4,
]

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
