# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: github-pages

      - uses: actions/checkout@v2
        with:
          ref: main

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: actions/cache@v1
        with:
          path: /nix/store
          key: store

      - name: Build site executable
        run: |
          nix-shell --run "ghc site.hs -threaded -rtsopts -with-rtsopts=-N"

      - name: Deploy
        run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            ./site rebuild
            git checkout github-pages
            git pull --rebase
            cp -a -v _site/. .
            git add --all
            git commit --allow-empty -m "[`date '+%F %T %Z'`] Site Update"
            git push origin github-pages:github-pages

